//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public int TaskId { get; set; }
        public string TaskName { get; set; }
        public Nullable<System.DateTime> TStartDate { get; set; }
        public Nullable<System.DateTime> TEndDate { get; set; }
        public Nullable<int> TPriority { get; set; }
        public Nullable<bool> TStatus { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ParentTaskName { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tblParent tblParent { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
